INSERT INTO States (StateAbbreviation, StateName) VALUES
('CDMX','Ciudad de México'),
('Ags.','Aguascalientes'),
('B.C.','Baja California'),
('B.C.S.','Baja California Sur'),
('Camp.','Campeche'),
('Chis.','Chiapas'),
('Chih.','Chihuahua'),
('Coah.','Coahuila de Zaragoza'),
('Col.','Colima'),
('Dgo.','Durango'),
('Gto.','Guanajuato'),
('Gro.','Guerrero'),
('Hgo.','Hidalgo'),
('Jal.','Jalisco'),
('M�x.','México'),
('Mich.','Michoacán de Ocampo'),
('Mor.','Morelos'),
('Nay.','Nayarit'),
('N.L.','Nuevo León'),
('Oax.','Oaxaca'),
('Pue.','Puebla'),
('Qro.','Querétaro Arteaga'),
('Q.R.','Quintana Roo'),
('S.L.P.','San Luis Potosí'),
('Sin.','Sinaloa'),
('Son.','Sonora'),
('Tab.','Tabasco'),
('Tamps.','Tamaulipas'),
('Tlax.','Tlaxcala'),
('Ver.','Veracruz'),
('Yuc.','Yucatán'),
('Zac.','Zacatecas');